AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  InspectorVulnFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.lambda_handler
      Runtime: python3.11
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - inspector2:ListFindings
                - inspector2:GetFindings
              Resource: '*'
